id: A55CEC57E
title: 'The Sun that Causes the Lotus of Intelligence to Bloom: In Praise of the Lineage
  of Gurus for the Noble Abhidharma'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:24:44.332387
  last_modified_at: 2022-03-01 01:24:44.332395
